name: 'Caprover: Login'
description: 'Log into Caprover instance and return authentication token'
inputs:
  caprover-password:
    description: Password for Caprover instance
    required: true
  caprover-otp:
    description: Log-in OTP if needed
    required: false
  caprover-url:
    description: The URL of the Caprover instance
    required: true
outputs:
  caprover-auth-token:
    description: The auth-token one can use to log into caprover
runs:
  using: 'node20'
  main: '../scripts/dist/caprover-login.js'
